version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint # Install dependencies needed for running the static analysis
  pre_build:
    commands:
      - python --version
      - pylint --disable=R,C0103,W0611,W0622t,E1101 $CODEBUILD_SRC_DIR/*.py
      - pylint --disable=R,C0103,W0611 $CODEBUILD_SRC_DIR/assignementproj/*.py
      - pylint --disable=R,C0103,W0611,W0622t,E1101 $CODEBUILD_SRC_DIR/CafeCoffeeDay/*.py
      
artifacts:
    files:
      - '**/*'
