# Generated by Django 2.1.15 on 2023-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeCoffeeDay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_ingredients', models.TextField()),
                ('item_category', models.CharField(choices=[('appetizers', 'Appetizers'), ('entrees', 'Entrees'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], max_length=50)),
            ],
        ),
    ]
